### PR TITLE
Add animations - Part 2

### LINKED ISSUE #10: Create animations

### PR DESCRIPTION
**Pull request by sandenson**
**Animation gifs**

_Backgrounds_

- Yoshi's Island 2 sublevel
sublevel_background

_Characters_

- Jumping piranha
jumping_piranha

- Koopa
    - Green
        - Shell-less
            - Kicked out of shell
green_kicked_out_of_shell
            - Shell-less moving
green_shell-less_moving
            - Stepped_on
green_stepped_on
        - With shell
            - Enters empty shell
green_entering_empty_shell
            - Turning
green_turning
            - With shell moving
green_shell_less_moving
    - Red
        - Shell-less
            - Kicked out of shell
red_stepped_on
            - Shell-less moving
red_kicked_out_of_shell
            - Stepped on
red_shell-less_moving
        - With shell
            - Enters empty shell
red_entering_empty_shell
            - Turning
red_turning
            - With shell moving
red_with_shell_moving

- Lookout chuck
    - Defeated
defeated
    - Hit
hit
    - Looking out
looking_out
    - Running
running

- Monty mole
    - Spawn
spawn
    - Move
move

- Map mario
    - Mounting Yoshi
mounting_yoshi
    - Normal
normal
    - Entering level
entering_level

- Yoshi: will be done later, since it seems like it's a pain in the ass to do.

_Objects_

- Berries
    - Red
pink
    - Pink
red

- Blinking grab block
blinking_grab_block

- Checkpoint
    - Light blue pole
light_blue_pole
    - Purple pole
purple_pole

- Coin
coin

- Koopa-shells
    - Red speen
red_speen
    - Green speen
green_speen

- Flying lucky block
flying_lucky_block

- Lucky block
lucky_block

- Lucky block coin
lucky_block_coin

- P-Switch
p-switch

- Vines head
vines_head

- Rotating block
rotating_block

- Yoshi coin
yoshi_coin

### CODE REVIEW

**Comment by Manuel-Antunes** [comment]
mande gifs de TODAS as animações

**Comment by sandenson** [comment]
> mande gifs de TODAS as animações

;-;

**Review by Manuel-Antunes — APPROVED** [review]
Mt boas animações

**Comment by sandenson** [comment]
> Mt boas animações

S-senpai >///<
image

**Pull request merged**
